//! `fsh-settings`: edits `config.toml` (keeping comments and formatting) and shows the
//! shell's status. The shell applies saved changes by itself, so this app never needs to
//! be running for Ferroshell to work — it's just a friendlier editor.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod ui {
    // Generated by slint-build; not our code to lint.
    #![allow(clippy::unwrap_used, clippy::todo)]
    slint::include_modules!();
}

mod form;

use ui::*;

use std::cell::RefCell;
use std::path::PathBuf;
use std::rc::Rc;
use std::time::{Duration, SystemTime};

use fsh_common::{paths, pipes};
use fsh_config::{Config, ConfigEditor, Edge, MonitorSel};
use fsh_widgets::{Layout, Origin, Registry};
use fsh_win::monitor::Monitor;
use serde_json::{Value, json};
use slint::{ModelRc, SharedString, StandardListViewItem, VecModel};

struct State {
    layout: Layout,
    config_path: PathBuf,
    config: Option<Config>,
    registry: Registry,
    monitors: Vec<Monitor>,
    themes: Vec<String>,
    panel: usize,
    widget: Option<usize>,
    addable: Vec<String>,
    last_mtime: Option<SystemTime>,
}

type Shared = Rc<RefCell<State>>;

fn main() -> anyhow::Result<()> {
    let _log = fsh_common::init_logging("settings").ok();
    let ui = SettingsWindow::new()?;
    let layout = Layout::new(paths::state_dir().join("builtin"), paths::config_dir());
    if let Err(e) = layout.extract_builtin() {
        tracing::warn!("could not extract built-in assets: {e}");
    }
    let state: Shared = Rc::new(RefCell::new(State {
        layout,
        config_path: paths::config_dir().join("config.toml"),
        config: None,
        registry: Registry::default(),
        monitors: vec![],
        themes: vec![],
        panel: 0,
        widget: None,
        addable: vec![],
        last_mtime: None,
    }));
    load(&state, &ui);
    connect(&state, &ui);
    poll_status(&ui);

    // Pick up edits made elsewhere (a text editor, pinning from the panel).
    let (st, weak) = (state.clone(), ui.as_weak());
    let timer = slint::Timer::default();
    timer.start(slint::TimerMode::Repeated, Duration::from_secs(1), move || {
        let changed = modified(&st.borrow().config_path) != st.borrow().last_mtime;
        if changed && let Some(ui) = weak.upgrade() {
            load(&st, &ui);
        }
    });

    ui.run()?;
    Ok(())
}

fn modified(p: &PathBuf) -> Option<SystemTime> {
    std::fs::metadata(p).and_then(|m| m.modified()).ok()
}

/// Re-read config, widgets, monitors and themes, then refresh everything on screen.
fn load(state: &Shared, ui: &SettingsWindow) {
    let b = ui.global::<Backend>();
    {
        let mut st = state.borrow_mut();
        st.last_mtime = modified(&st.config_path);
        match std::fs::read_to_string(&st.config_path).map_err(|e| e.to_string()).and_then(|t| Config::parse(&t).map_err(|e| e.0)) {
            Ok(c) => {
                st.config = Some(c);
                b.set_banner("".into());
            }
            Err(e) => {
                st.config = None;
                b.set_banner(format!("config.toml has an error, so it can't be edited here until it's fixed: {e}").into());
            }
        }
        let theme_widgets = st
            .config
            .as_ref()
            .and_then(|c| st.layout.theme_dir(&c.theme))
            .map(|d| d.join("widgets"));
        let mut roots = vec![(st.layout.user_widgets(), Origin::User)];
        roots.extend(theme_widgets.map(|d| (d, Origin::Theme)));
        roots.push((st.layout.builtin_widgets(), Origin::Builtin));
        st.registry = Registry::scan(&roots);
        st.monitors = fsh_win::monitor::monitors();

        let mut themes = vec!["auto".to_owned()];
        for dir in [st.layout.builtin_themes(), st.layout.user_themes()] {
            if let Ok(entries) = std::fs::read_dir(dir) {
                for e in entries.flatten() {
                    let name = e.file_name().to_string_lossy().into_owned();
                    if e.path().join("theme.toml").is_file() && !themes.contains(&name) {
                        themes.push(name);
                    }
                }
            }
        }
        st.themes = themes;
        let mut addable: Vec<(String, String)> =
            st.registry.packages().map(|p| (p.manifest.name.clone(), p.manifest.id.clone())).collect();
        addable.sort();
        st.addable = addable.iter().map(|(_, id)| id.clone()).collect();
        b.set_addable_widgets(model(addable.into_iter().map(|(name, _)| SharedString::from(name))));

        let n_panels = st.config.as_ref().map_or(0, |c| c.panels.len());
        if st.panel >= n_panels {
            st.panel = n_panels.saturating_sub(1);
        }
        let n_widgets = st.config.as_ref().and_then(|c| c.panels.get(st.panel)).map_or(0, |p| p.widgets.len());
        if st.widget.is_some_and(|w| w >= n_widgets) {
            st.widget = n_widgets.checked_sub(1);
        }
    }
    refresh(state, ui);
}

fn model<T: Clone + 'static>(items: impl IntoIterator<Item = T>) -> ModelRc<T> {
    ModelRc::new(VecModel::from(items.into_iter().collect::<Vec<T>>()))
}

fn edge_index(e: Edge) -> i32 {
    match e {
        Edge::Top => 0,
        Edge::Bottom => 1,
        Edge::Left => 2,
        Edge::Right => 3,
    }
}

fn monitor_label(sel: MonitorSel) -> String {
    match sel {
        MonitorSel::All => "all monitors".into(),
        MonitorSel::Primary => "primary monitor".into(),
        MonitorSel::Index(i) => format!("monitor {i}"),
    }
}

/// Push the current state into the UI.
fn refresh(state: &Shared, ui: &SettingsWindow) {
    let st = state.borrow();
    let b = ui.global::<Backend>();
    let Some(config) = st.config.as_ref() else {
        b.set_panels(model(Vec::<StandardListViewItem>::new()));
        b.set_widgets(model(Vec::<WidgetRow>::new()));
        b.set_fields(model(Vec::<Field>::new()));
        return;
    };

    let l = &config.launcher;
    b.set_l_windows_key(l.windows_key);
    b.set_l_width(l.width as i32);
    b.set_l_height(l.height as i32);
    b.set_l_show_recent(l.show_recent);
    b.set_l_favourites(l.favourites.join("\n").into());
    b.set_l_web_search(l.web_search.as_str().into());
    let has = |a: &str| l.power_actions.iter().any(|p| p == a);
    b.set_l_lock(has("lock"));
    b.set_l_sleep(has("sleep"));
    b.set_l_restart(has("restart"));
    b.set_l_shutdown(has("shutdown"));
    b.set_l_logout(has("logout"));

    b.set_panels(model(config.panels.iter().enumerate().map(|(i, p)| {
        StandardListViewItem::from(SharedString::from(format!(
            "Panel {} ({}, {})",
            i + 1,
            format!("{:?}", p.edge).to_lowercase(),
            monitor_label(p.monitor)
        )))
    })));
    b.set_current_panel(st.panel as i32);

    let mut monitors = vec!["All monitors".to_owned(), "Primary monitor".to_owned()];
    monitors.extend(st.monitors.iter().enumerate().map(|(i, m)| {
        format!("Monitor {i}: {}×{}{}", m.rect.width(), m.rect.height(), if m.primary { " (primary)" } else { "" })
    }));
    b.set_monitor_options(model(monitors.into_iter().map(SharedString::from)));

    let Some(panel) = config.panels.get(st.panel) else {
        b.set_widgets(model(Vec::<WidgetRow>::new()));
        b.set_fields(model(Vec::<Field>::new()));
        b.set_form_title("".into());
        return;
    };
    b.set_panel(PanelInfo {
        edge_index: edge_index(panel.edge),
        monitor_index: match panel.monitor {
            MonitorSel::All => 0,
            MonitorSel::Primary => 1,
            MonitorSel::Index(i) => 2 + i as i32,
        },
        thickness: panel.thickness as i32,
        floating: panel.floating,
    });

    b.set_widgets(model(panel.widgets.iter().map(|w| match st.registry.get(&w.id) {
        Ok(pkg) => WidgetRow {
            id: w.id.as_str().into(),
            name: pkg.manifest.name.as_str().into(),
            detail: format!("{}  ·  {}", w.id, format!("{:?}", pkg.origin).to_lowercase()).into(),
            error: "".into(),
        },
        Err(e) => WidgetRow { id: w.id.as_str().into(), name: w.id.as_str().into(), detail: "".into(), error: e.into() },
    })));
    b.set_current_widget(st.widget.map_or(-1, |w| w as i32));

    match st.widget.and_then(|i| panel.widgets.get(i)) {
        Some(entry) => match st.registry.get(&entry.id) {
            Ok(pkg) => {
                b.set_form_title(pkg.manifest.name.as_str().into());
                b.set_form_description(pkg.manifest.description.as_str().into());
                b.set_fields(model(form::fields(&pkg.manifest, &entry.settings)));
            }
            Err(e) => {
                b.set_form_title(entry.id.as_str().into());
                b.set_form_description(e.into());
                b.set_fields(model(Vec::<Field>::new()));
            }
        },
        None => {
            b.set_form_title("Widget settings".into());
            b.set_form_description("Select a widget to change its settings.".into());
            b.set_fields(model(Vec::<Field>::new()));
        }
    }

    b.set_themes(model(st.themes.iter().map(|t| SharedString::from(t.as_str()))));
    b.set_theme_index(st.themes.iter().position(|t| *t == config.theme).map_or(-1, |i| i as i32));
}

/// Apply an edit to config.toml and reload. Errors go to the status line.
fn edit(state: &Shared, ui: &SettingsWindow, f: impl FnOnce(&mut ConfigEditor, &State) -> Result<(), String>) {
    let result = {
        let st = state.borrow();
        ConfigEditor::load(&st.config_path).and_then(|mut ed| {
            f(&mut ed, &st)?;
            // Never write something the shell would reject.
            Config::parse(&ed.to_text()).map_err(|e| e.0)?;
            ed.save(&st.config_path)
        })
    };
    let b = ui.global::<Backend>();
    match result {
        Ok(()) => b.set_status("Saved. The shell applies changes automatically.".into()),
        Err(e) => b.set_status(format!("Not saved: {e}").into()),
    }
    load(state, ui);
}

fn call_async(pipe: &'static str, method: &'static str, params: Value) {
    std::thread::spawn(move || {
        if let Err(e) = fsh_ipc::pipe::call(pipe, method, params, Duration::from_secs(5)) {
            tracing::warn!("{method}: {e:#}");
        }
    });
}

fn connect(state: &Shared, ui: &SettingsWindow) {
    let b = ui.global::<Backend>();
    macro_rules! on {
        ($setter:ident, |$st:ident, $ui:ident $(, $arg:ident : $ty:ty)*| $body:block) => {{
            let (state, weak) = (state.clone(), ui.as_weak());
            b.$setter(move |$($arg: $ty),*| {
                if let Some($ui) = weak.upgrade() {
                    let $st = &state;
                    $body
                }
            });
        }};
    }

    on!(on_select_panel, |st, ui, i: i32| {
        st.borrow_mut().panel = i.max(0) as usize;
        st.borrow_mut().widget = None;
        refresh(st, &ui);
    });
    on!(on_add_panel, |st, ui| {
        edit(st, &ui, |ed, _| {
            ed.add_panel("top", &["org.ferroshell.spacer", "org.ferroshell.clock"]);
            Ok(())
        });
        let n = st.borrow().config.as_ref().map_or(0, |c| c.panels.len());
        st.borrow_mut().panel = n.saturating_sub(1);
        refresh(st, &ui);
    });
    on!(on_remove_panel, |st, ui| {
        let p = st.borrow().panel;
        edit(st, &ui, |ed, _| ed.remove_panel(p));
    });
    on!(on_set_edge, |st, ui, i: i32| {
        let p = st.borrow().panel;
        let edge = ["top", "bottom", "left", "right"].get(i as usize).copied().unwrap_or("bottom");
        edit(st, &ui, |ed, _| ed.set_panel(p, "edge", edge));
    });
    on!(on_set_monitor, |st, ui, i: i32| {
        let p = st.borrow().panel;
        edit(st, &ui, |ed, _| match i {
            0 => ed.set_panel(p, "monitor", "all"),
            1 => ed.set_panel(p, "monitor", "primary"),
            n => ed.set_panel(p, "monitor", i64::from(n - 2)),
        });
    });
    on!(on_set_thickness, |st, ui, v: i32| {
        let p = st.borrow().panel;
        edit(st, &ui, |ed, _| ed.set_panel(p, "thickness", i64::from(v)));
    });
    on!(on_set_floating, |st, ui, v: bool| {
        let p = st.borrow().panel;
        edit(st, &ui, |ed, _| ed.set_panel(p, "floating", v));
    });

    on!(on_select_widget, |st, ui, i: i32| {
        st.borrow_mut().widget = (i >= 0).then_some(i as usize);
        refresh(st, &ui);
    });
    on!(on_add_widget, |st, ui, i: i32| {
        let (p, id, at) = {
            let s = st.borrow();
            let at = s.widget.map_or(usize::MAX, |w| w + 1);
            (s.panel, s.addable.get(i.max(0) as usize).cloned(), at)
        };
        if let Some(id) = id {
            edit(st, &ui, |ed, _| ed.add_widget(p, at, &id));
            let n = st.borrow().config.as_ref().and_then(|c| c.panels.get(p)).map_or(0, |p| p.widgets.len());
            st.borrow_mut().widget = Some(at.min(n.saturating_sub(1)));
            refresh(st, &ui);
        }
    });
    on!(on_remove_widget, |st, ui| {
        let (p, w) = (st.borrow().panel, st.borrow().widget);
        if let Some(w) = w {
            edit(st, &ui, |ed, _| ed.remove_widget(p, w));
        }
    });
    on!(on_move_widget, |st, ui, delta: i32| {
        let (p, w) = (st.borrow().panel, st.borrow().widget);
        if let Some(w) = w {
            let to = (w as i32 + delta).max(0) as usize;
            edit(st, &ui, |ed, _| ed.move_widget(p, w, to));
            st.borrow_mut().widget = Some(to);
            refresh(st, &ui);
        }
    });

    on!(on_set_text, |st, ui, key: SharedString, value: SharedString| {
        form_edit(st, &ui, &key, form::Input::Text(value.to_string()));
    });
    on!(on_set_bool, |st, ui, key: SharedString, value: bool| {
        form_edit(st, &ui, &key, form::Input::Bool(value));
    });
    on!(on_set_number, |st, ui, key: SharedString, value: i32| {
        form_edit(st, &ui, &key, form::Input::Int(i64::from(value)));
    });
    on!(on_set_option, |st, ui, key: SharedString, value: i32| {
        form_edit(st, &ui, &key, form::Input::Option(value.max(0) as usize));
    });
    on!(on_reset_field, |st, ui, key: SharedString| {
        let (p, w) = (st.borrow().panel, st.borrow().widget);
        if let Some(w) = w {
            edit(st, &ui, |ed, _| ed.reset_widget_setting(p, w, &key));
        }
    });

    on!(on_preview_theme, |st, ui, i: i32| {
        if let Some(name) = st.borrow().themes.get(i.max(0) as usize).cloned() {
            call_async(pipes::SHELL, "set_theme", json!({ "name": name }));
            ui.global::<Backend>().set_status(format!("Previewing {name}. Apply to keep it.").into());
        }
    });
    on!(on_apply_theme, |st, ui, i: i32| {
        if let Some(name) = st.borrow().themes.get(i.max(0) as usize).cloned() {
            edit(st, &ui, |ed, _| {
                ed.set_top("theme", name.as_str());
                Ok(())
            });
            call_async(pipes::SHELL, "set_theme", json!({ "name": null }));
        }
    });

    on!(on_reload_shell, |_st, ui| {
        call_async(pipes::SHELL, "reload", Value::Null);
        ui.global::<Backend>().set_status("Reloading…".into());
    });
    on!(on_restart_shell, |_st, ui| {
        call_async(pipes::SESSION, "restart", Value::Null);
        ui.global::<Backend>().set_status("Restarting the shell…".into());
    });
    on!(on_safe_mode, |_st, ui, on: bool| {
        call_async(pipes::SESSION, "safe_mode", json!({ "on": on }));
        ui.global::<Backend>().set_status(if on { "Restarting in safe mode…" } else { "Leaving safe mode…" }.into());
    });
    on!(on_open_path, |st, ui, what: SharedString| {
        let s = st.borrow();
        let (program, path) = match what.as_str() {
            "config" => ("notepad.exe", s.config_path.clone()),
            "widgets" => ("explorer.exe", s.layout.user_widgets()),
            "themes" => ("explorer.exe", s.layout.user_themes()),
            "builtin-widgets" => ("explorer.exe", s.layout.builtin_widgets()),
            "builtin-themes" => ("explorer.exe", s.layout.builtin_themes()),
            _ => ("explorer.exe", paths::log_dir()),
        };
        if program == "explorer.exe" {
            let _ = std::fs::create_dir_all(&path);
        }
        if let Err(e) = std::process::Command::new(program).arg(&path).spawn() {
            ui.global::<Backend>().set_status(format!("Could not open {}: {e}", path.display()).into());
        }
    });
    on!(on_set_launcher_bool, |st, ui, key: SharedString, v: bool| {
        edit(st, &ui, |ed, _| {
            ed.set_launcher(&key, v);
            Ok(())
        });
    });
    on!(on_set_launcher_int, |st, ui, key: SharedString, v: i32| {
        edit(st, &ui, |ed, _| {
            ed.set_launcher(&key, i64::from(v));
            Ok(())
        });
    });
    on!(on_set_launcher_text, |st, ui, key: SharedString, v: SharedString| {
        edit(st, &ui, |ed, _| {
            if key == "favourites" {
                let items: Vec<String> = v.lines().map(str::trim).filter(|l| !l.is_empty()).map(str::to_owned).collect();
                ed.set_launcher_list("favourites", &items);
            } else {
                ed.set_launcher(&key, v.trim());
            }
            Ok(())
        });
    });
    on!(on_set_power, |st, ui, id: SharedString, on: bool| {
        edit(st, &ui, |ed, s| {
            let current = s.config.as_ref().map(|c| c.launcher.power_actions.clone()).unwrap_or_default();
            // Keep the standard order.
            let list: Vec<String> = fsh_config::config::POWER_ACTIONS
                .iter()
                .filter(|a| if **a == id.as_str() { on } else { current.iter().any(|c| c == *a) })
                .map(|a| (*a).to_owned())
                .collect();
            ed.set_launcher_list("power-actions", &list);
            Ok(())
        });
    });
    on!(on_refresh, |st, ui| {
        load(st, &ui);
    });
}

fn form_edit(state: &Shared, ui: &SettingsWindow, key: &str, input: form::Input) {
    let (p, w) = (state.borrow().panel, state.borrow().widget);
    let Some(w) = w else { return };
    edit(state, ui, |ed, st| {
        let id = &st.config.as_ref().and_then(|c| c.panels.get(p)).and_then(|p| p.widgets.get(w)).ok_or("no such widget")?.id;
        let pkg = st.registry.get(id)?;
        let field = pkg.manifest.config.get(key).ok_or_else(|| format!("unknown setting {key}"))?;
        match form::to_value(&field.kind, input)? {
            form::Value::One(v) => ed.set_widget_setting(p, w, key, v),
            form::Value::List(items) => ed.set_widget_list(p, w, key, &items),
        }
    });
}

/// Poll the shell for status on a background thread every couple of seconds.
fn poll_status(ui: &SettingsWindow) {
    let weak = ui.as_weak();
    std::thread::spawn(move || {
        loop {
            let shell = fsh_ipc::pipe::call(pipes::SHELL, "dump_state", Value::Null, Duration::from_millis(1500));
            let session = fsh_ipc::pipe::call(pipes::SESSION, "status", Value::Null, Duration::from_millis(1500));
            let weak = weak.clone();
            let alive = slint::invoke_from_event_loop(move || {
                let Some(ui) = weak.upgrade() else { return };
                let b = ui.global::<Backend>();
                let (text, plugins) = describe(shell.ok(), session.ok());
                b.set_shell_state(text.into());
                b.set_plugins(model(plugins));
            });
            if alive.is_err() {
                return;
            }
            std::thread::sleep(Duration::from_secs(2));
        }
    });
}

fn describe(shell: Option<Value>, session: Option<Value>) -> (String, Vec<PluginRow>) {
    let mut lines = Vec::new();
    match &session {
        Some(s) => lines.push(format!(
            "Supervisor: {}{}, {} restart(s).",
            s["state"].as_str().unwrap_or("?"),
            if s["safe_mode"].as_bool() == Some(true) { " (SAFE MODE)" } else { "" },
            s["restarts"].as_u64().unwrap_or(0)
        )),
        None => lines.push("Supervisor: not running (start Ferroshell with fsh-session.exe).".into()),
    }
    let mut plugins = Vec::new();
    match &shell {
        Some(s) => {
            let panels = s["panels"].as_array().map_or(0, Vec::len);
            let windows = s["windows"].as_array().map_or(0, Vec::len);
            lines.push(format!("Shell: {panels} panel(s), tracking {windows} window(s), theme {}.", s["theme"]["name"].as_str().unwrap_or("?")));
            if let Some(e) = s["config_error"].as_str() {
                lines.push(format!("Config error (using last working config): {e}"));
            }
            for p in s["plugins"].as_array().into_iter().flatten() {
                plugins.push(PluginRow {
                    id: p["id"].as_str().unwrap_or_default().into(),
                    state: p["state"].as_str().unwrap_or_default().into(),
                    restarts: p["restarts"].as_i64().unwrap_or(0) as i32,
                    error: p["last_error"].as_str().unwrap_or_default().into(),
                });
            }
        }
        None => lines.push("Shell: not running.".into()),
    }
    (lines.join("\n"), plugins)
}
